### ISSUE TITLE
[Question] What is `Highlight non-function Methods` feature

### ISSUE THREAD

**Issue by tjx666** [zardoy/typescript-vscode-plugins#110]
I still can't understand after read the documation.

**Comment by zardoy** [comment]
Good question, feel free to ask more.

Probably it will be much easier to understand with screenshot:

<img width="345" alt="non-function-methods" src="https://user-images.githubusercontent.com/46503702/222369546-19d36849-2942-4bc5-b5b7-a07d11ad3e7b.png">

This is especially useful for declarations like this (some npm libs use it):

```ts
declare const readJsonFile: {
    (path: string): Promise<unknown>
    sync(path: string): unknown
}

readJsonFile./**/
```

This method of adding stars I call highlighting ([IntelliCode](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode) uses similar method to highlight commonly used suggestions)

Also probably it also makes sense to add logic to force these suggestions on top, but most of the they are already here and I don't see a demand for this.

**Comment by tjx666** [comment]
@zardoy 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/222886465-3629c1d6-9a6b-4553-aa54-ca09182c9ab0.png">

**Comment by zardoy** [comment]
@tjx666 so as I understand you want these *non-function methdos* to be **always displayed at the top**? Not a problem

**Comment by tjx666** [comment]
no, I mean there are two stars there, maybe we should only show one star

**Comment by zardoy** [comment]
As I said in https://github.com/zardoy/typescript-vscode-plugins/issues/110#issuecomment-1451466679

> This method of adding stars I call highlighting (IntelliCode uses similar method to highlight commonly used suggestions)

[IntelliCode](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode) adds another star + space in names for commonly used suggestions.

But yes, we can skip adding our star :) But then we would end up with having different stars in different completions 🤔
