### ISSUE TITLE
Volar 1.6+ support 

### ISSUE THREAD

**Issue by maIIady** [zardoy/typescript-vscode-plugins#126]
Hello, I recently upgraded `Volar` from v1.4.4 to v1.6+, but it seems that the support for it is no longer functioning properly. It looks like there is a more complex underlying issue than just with Volar [config setting change](https://github.com/vuejs/language-tools/compare/v1.4.4...v1.6.0#diff-64b18deaf8771f5e37f93b3edcb4b4355e19ab5ce51af407fb73882146e4c9f3R411) (`volar.vueserver.configFilePath` -> `vue.server.configFilePath`)

I personally looked into it but I wasn't able to find any results. It seems as though the extension isn't activated at all, as I didn't see either the message ["Ts Essential Plugins Activated"](https://github.com/zardoy/typescript-vscode-plugins/blob/develop/typescript/src/volarConfig.ts#L35) or ["Failed to activate tsEssentialPlugins"](https://github.com/zardoy/typescript-vscode-plugins/blob/develop/typescript/src/volarConfig.ts#LL54C23-L54C60) in the extension output.

Could you please provide some assistance or advice on what could break?

P.S. Tested it with an empty profile with only this settings enabled:
`code --list-extensions` output:
```
Vue.volar
zardoy.ts-essential-plugins
```
Related settings:
```json
{
  "tsEssentialPlugins.enableVueSupport": true,
  "vue.server.configFilePath": "<PATH>"
}
```

**Comment by zardoy** [comment]
> I personally looked into it but I wasn't able to find any results. It seems as though the extension isn't activated at all

I updated setting and I see `TS Essentials Plugins activated` message in Vue Semantic Server output. It works.

**Comment by maIIady** [comment]
Ok, sorry, this indeed works :)

But [setting to remove component from defintions broke](https://github.com/zardoy/typescript-vscode-plugins/blob/develop/typescript/src/definitions.ts#L143-L145)

E.g. hovering over here https://github.com/maIIady/pinia-test/blob/master/src/App.vue#L4

Gonna end up with this output - 
![image](https://user-images.githubusercontent.com/74474615/235893114-36ac73ec-6d8e-4451-b10a-d16b84d933b7.png)


So there is no more [__VLS_componentsOption](https://github.com/zardoy/typescript-vscode-plugins/blob/7c8879f78a8aa96aa209b05d48a645a0d5fc82f1/typescript/src/definitions.ts#LL144C1-L144C1) to filter. This is mostly volar's issue and, as I can see, there is not way to handle it on our side (or not?)

PS. You can close the issue, thanks for help

**Comment by zardoy** [comment]
Yes let's include this improvements for volar, and also let's include fix for code actions formatting

**Comment by maIIady** [comment]
Can you provide some tips how to filter this refs? And I don't get what `fix for code actions formatting` you mentioned?

> Yes let's include this improvements for volar, and also let's include fix for code actions formatting Update: sorry didn't answer your question. No, there is still a way to filter these defs from our side

Btw, is there a chance we could meet somewhere to work on it and maybe some other features?

**Comment by zardoy** [comment]
> Can you provide some tips how to filter this refs?

So far I was using this detection https://github.com/zardoy/typescript-vscode-plugins/blob/706ec5952390212edb4d27b4aa6b9637f3c5b4ac/typescript/src/completionsAtPosition.ts#L274

> And I don't get what `fix for code actions formatting` you mentioned?

https://github.com/vuejs/language-tools/issues/2425 , thought it might also annoy you. If it doesn't then there is no priority for this one

> Btw, is there a chance we could meet somewhere to work on it and maybe some other features?

Ofc, just as always :)
