### ISSUE TITLE
Question about some VS Code settings

### ISSUE THREAD

**Issue by svipas** [zardoy/typescript-vscode-plugins#143]
So as far as I can understand I can remove these settings:

```json
  "editor.suggest.localityBonus": true,
  "typescript.suggest.completeFunctionCalls": true,
  "javascript.suggest.completeFunctionCalls": true,
```

Because complete function calls is used by default by this extension and I additionally added `"tsEssentialPlugins.suggestions.localityBonus": true` since it works better.

Or I still should keep them?

**Comment by zardoy** [comment]
> Or I still should keep them?

Well, you most probably see plugin's features work without enabling these settings. And you're absolutely right, these two features from the plugin replace builtin functionality, so you don't have to keep them enabled.

Here is the comparison:

| VS Code Builtin                                                                                            | TypeScript Essentials Plugins                                                                              |
| ---------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------- |
| `editor.suggest.localityBonus` - Uses text-based matching, annoying in some cases                          | `tsEssentialPlugins.suggestions.localityBonus` - Uses **actual definition** position                       |
| `typescript.suggest.completeFunctionCalls` - Uses completion tooltip, works only with function declaration | `tsEssentialPlugins.enableMethodSnippets` - Uses **type signature**, always precise with *any function* |

(I think it should be really included in readme)


Though, for now `tsEssentialPlugins.suggestions.localityBonus` doesn't sort auto-import suggestions e.g. it doesn't mean that suggestion with auto-import path `./foo` (local path) will be higher than `foo` (external module).

**Comment by svipas** [comment]
Thanks a lot for explanation!
