### ISSUE TITLE
Keywords Insert Text adds 2 spaces instead of 1

### ISSUE THREAD

**Issue by svipas** [zardoy/typescript-vscode-plugins#144]
As title says, I don't know why but it adds 2 spaces instead of 1. It is really cool setting and I love it, but I can't use it, because I manually need to delete 1 space...

And, it happens not always, for e.g. in Untitled file it always uses 1 space.

Steps to reproduce:
1. Create file `a.ts`
2. Reload window
3. Trigger suggest widget and select `const`
4. Press Tab and you will see 2 or more spaces instead of 1

<img width="62" alt="image" src="https://github.com/zardoy/typescript-vscode-plugins/assets/10441177/ba8984c9-8600-426c-8b0b-cdca42cecff7">

What is also weird that it happens for few times and it starts to work normal again, as mentioned it might be harder to repro, but it is possible especially after reloading VS Code window.

**Comment by zardoy** [comment]
I cannot reproduce at all, but in theory TypeScript can cache incomplete lists. Can you try installing extension from https://github.com/zardoy/typescript-vscode-plugins/actions/runs/5525742725 ?
