### ISSUE TITLE
Method snippets insert text in class skips "this"

### ISSUE THREAD

**Issue by svipas** [zardoy/typescript-vscode-plugins#148]
If I enable `"tsEssentialPlugins.methodSnippetsInsertText": "all"` and I'm in TS class which contains function and I select it from the completions list after pressing Tab it is completed without `this` for e.g. `foo()` instead of `this.foo()`.

List with suggestion:
<img width="497" alt="image" src="https://github.com/zardoy/typescript-vscode-plugins/assets/10441177/0df1ad46-95d3-42db-a044-624f1e043d12">

After completion:
<img width="277" alt="image" src="https://github.com/zardoy/typescript-vscode-plugins/assets/10441177/40ed3021-dee4-4792-b20c-f844d78c5a60">

If I disable that setting and let VS Code handle it, it includes `this`:

List with suggestion:
<img width="301" alt="image" src="https://github.com/zardoy/typescript-vscode-plugins/assets/10441177/888144b0-6848-46d8-83a6-22ce16dd203c">

After completion:
<img width="431" alt="image" src="https://github.com/zardoy/typescript-vscode-plugins/assets/10441177/1cf9de48-697b-40ff-b56d-3e00f70039d9">

**Comment by zardoy** [comment]
This must annoying, so I decided to make a release for this one.

**Comment by svipas** [comment]
Nice, thanks!
