### ISSUE TITLE
Add ability to hide "[essentials] Fix all TypeScript" source action

### ISSUE THREAD

**Issue by svipas** [zardoy/typescript-vscode-plugins#150]
As title says, please add a setting which could hide this source action.

<img width="265" alt="image" src="https://github.com/zardoy/typescript-vscode-plugins/assets/10441177/4aa55021-fd9b-46b9-8ab0-e0c02f3e2a09">

**Comment by zardoy** [comment]
Hmm, but I’m not sure what you motivation… I mean other extensions (such as TypeScript) doesn’t propose such setting, why do you have to use this menu? Why don’t you bind key binding to fix all command instead? Though there is a way to disable this plugin in codeactions on save.

**Comment by svipas** [comment]
Yeah, but TS extension is built-in and I expect those actions to be here, your extension contributes additional actions.

The reason why I'm using this menu is that I like to press custom shortcut (shift+option+s) and I pickup first item "Remove Unused Imports". I know I can bind it to do it instead of popping up source action, but I like it this way 🤷 

So that's why I thought, maybe you could add a setting to disable it?

**Comment by zardoy** [comment]
> Yeah, but TS extension is built-in and I expect those actions to be here, your extension contributes additional actions.


Okay, it can eslint as well and I feel like vscode should have general interface for these cases. 

> So that's why I thought, maybe you could add a setting to disable it?


Yes, of course, I just wanted to propose other solution first, anyway it is not hard to add a way to disable it via setting. Currently, I'm thinking about the following:




![image](https://github.com/zardoy/typescript-vscode-plugins/assets/46503702/b5b17adb-820c-40d7-ab98-74d6d1a4b796)

**Comment by zardoy** [comment]
I didn't release it yet so feel free to make proposals

**Comment by svipas** [comment]
Yeah that works for me, thanks!

**Comment by zardoy** [comment]
But note that I used the value to `fixAllInFileSourceAction`, will release this chagne soon.
