### ISSUE TITLE
to destruct, from destruct 

### ISSUE THREAD

**Issue by zardoy** [zardoy/typescript-vscode-plugins#167]
- check correct what names would be technically correct
- kind: `refactor.rewrite.add-destruct` and `refactor.rewrite.from-destruct`

Code:

Edge case with to destruct:
```ts
const a = {foo: 5, bar: 8}

const b = [a.foo] // [...] - activation pos range

const c = a
```

```ts
const a = {foo: 5, bar: 8}
const { foo } = a

const b = foo

const c = a
```

With first implementation we can skip hadling this advanced functionality.

**Comment by zardoy** [comment]
@maIIady I'm going to make a new release after this one is merged (and probably https://github.com/zardoy/typescript-vscode-plugins/issues/168), okay?

**Comment by Ilanaya** [comment]
> @maIIady I'm going to make a new release after this one is merged (and probably #168), okay?

Np, I'll work on this today's night

**Comment by zardoy** [comment]
I think we should also show rewrite to destruct refactoring only when the cursor is on the declaration (we can check it by getting symbol of node), so we don’t annoy with it. Rewrite to destruct should be explicit range selection I think

**Comment by zardoy** [comment]
https://github.com/zardoy/typescript-vscode-plugins/pull/175#issuecomment-1784488243
3. handle `this` inside of functions (to destruct)

**Comment by Ilanaya** [comment]
4. Handle object prop shorthand
```ts
        const { tag, componentInstance, componentOptions } = vnodeToCache
        cache[keyToCache] = {
          name: _getComponentName(componentOptions),
          tag,
          componentInstance
        }
```
Now results in broken code:
```ts
     const newVariable = vnodeToCache
        cache[keyToCache] = {
          name: _getComponentName(newVariable.componentOptions),
          newVariable.tag,
          newVariable.componentInstance
        }
```
