### ISSUE TITLE
Attributes auto suggest, props inlay hints and better declare missing properties code action 

### ISSUE THREAD

**Issue by tjx666** [zardoy/typescript-vscode-plugins#208]
You can check the extension https://github.com/xicunyang/ts-space-prompt, the feature of that extension is awesome. But it conflict with this extension, and the implementation of that extension seems not very good, it copy whole official ts plugin code. I recommend to migrate the feature of that extension to this extension.

<img width="995" alt="image" src="https://github.com/zardoy/typescript-vscode-plugins/assets/41773861/2d20010d-7953-4512-b164-3c037acfc149">

Another similar feature request is inspire from volarjs, show required props hint:

<img width="1512" alt="image" src="https://github.com/zardoy/typescript-vscode-plugins/assets/41773861/3aa798dd-13f8-4a32-bd39-0be923c94b74">

I think you're very impressive, big bro, and also very passionate about VSCode extension development. If you have the time, consider integrating these features into this plugin.

**Comment by tjx666** [comment]
@zardoy @Ilanaya update description

**Comment by Ilanaya** [comment]
Thanks! I'll be able to work on your requests tomorrow

**Comment by zardoy** [comment]
Hey, sorry for the delayed response.

> You can check the extension [xicunyang/ts-space-prompt](https://github.com/xicunyang/ts-space-prompt), the feature of that extension is awesome

What features from this extension do you think are awesome? Please be specific and I'll migrate them for you without any problems.

- auto-trigger completions (trigger attribute completions on space, can also auto-trigger object suggestions on comma and so on)
- fill in missing attributes or properties. There is already builtin "declare missing properties" code fix, we can just improve it by adding tab stops. @Ilanaya we might also consider migrating [insertCompletions feature](https://github.com/zardoy/vscode-experiments/blob/5202f4df5f3bfbeb67fffd5ae1b2f53946ebda85/src/features/insertCompletions.ts#L14) from experiments extension which is more powerful and useful

@tjx666 please let us know if that's what you need

Also, I don't think it would make sense to fix compatibility with the aforementioned extension.

**Comment by tjx666** [comment]
Yes, you understand my need very clear. What's more is that mising props inlay hints

**Comment by zardoy** [comment]
> Yes, you understand my need very clear. What's more is that mising props inlay hints

Okay, + inlay hints of missing props for react components. I'll implement these 3 features within 3 next days, would be awesome if you could tell us how we can better present these features for better discoverability!

**Comment by zardoy** [comment]
Adding declare missing codefix that adds
<img width="482" alt="image" src="https://github.com/zardoy/typescript-vscode-plugins/assets/46503702/e4e45c70-61bd-4815-b539-743f6232df69">
<img width="247" alt="image" src="https://github.com/zardoy/typescript-vscode-plugins/assets/46503702/a9daf50a-5f25-4efd-a2b2-d254c3b0e163">

can hide the original with
```
"tsEssentialPlugins.removeCodeFixes.codefixes": [
        "fixMissingFunctionDeclaration",
        "fixMissingAttributes"
]
```
or maybe I should do it by default

---

added inlay hints (disabled by default):
<img width="241" alt="image" src="https://github.com/zardoy/typescript-vscode-plugins/assets/46503702/1c79bd3a-d513-4cda-8508-d3e2b696d041">

---

Added auto completion trigger for attributes (enabled by default)

**Comment by tjx666** [comment]
@zardoy 

> we can just improve it by adding tab stops

seems doesn't work

**Comment by tjx666** [comment]
volar support double click the missing props to add it:


https://github.com/zardoy/typescript-vscode-plugins/assets/41773861/2428f9ee-e924-4d17-bf22-312c4ced60d2

**Comment by tjx666** [comment]
@zardoy had you checked this?

> @zardoy
> 
> > we can just improve it by adding tab stops
> 
> seems doesn't work

**Comment by zardoy** [comment]
> @zardoy had you checked this?

No, maybe @Ilanaya can

**Comment by thrivingproject** [comment]
> Adding declare missing codefix that adds <img alt="image" width="482" src="https://private-user-images.githubusercontent.com/46503702/333452485-e4e45c70-61bd-4815-b539-743f6232df69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDYxNTkzNjAsIm5iZiI6MTc0NjE1OTA2MCwicGF0aCI6Ii80NjUwMzcwMi8zMzM0NTI0ODUtZTRlNDVjNzAtNjFiZC00ODE1LWI1MzktNzQzZjYyMzJkZjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTAyVDA0MTEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZmVkZjVjNTIzNDhlNmNjMmI1MTM2Yzk4MGYyNmJhZDA3Njc1OTg0ZWI1YzcxMzIwYmVlMTE3OTM4MjQ5M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kxG35andO0HdMeVcPxjSqdetuDEgEiFHkQ0Ja5t_PqY"> <img alt="image" width="247" src="https://private-user-images.githubusercontent.com/46503702/333452566-a9daf50a-5f25-4efd-a2b2-d254c3b0e163.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDYxNTkzNjAsIm5iZiI6MTc0NjE1OTA2MCwicGF0aCI6Ii80NjUwMzcwMi8zMzM0NTI1NjYtYTlkYWY1MGEtNWYyNS00ZWZkLWEyYjItZDI1NGMzYjBlMTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTAyVDA0MTEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMTZiODdhM2VlZDI1ZDhjZjE3ODNjZTM1ZDA2YjkxNTU4N2E5YmQ0MWE2ZDdkNmI2MTU5NTcxYjc4OGU0NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.epnKP0P-4r8k_xF5cdFLa41vaj8OUk1okGe76LtN2x8">
> 
> can hide the original with
> 
> ```
> "tsEssentialPlugins.removeCodeFixes.codefixes": [
>         "fixMissingFunctionDeclaration",
>         "fixMissingAttributes"
> ]
> ```
> 
> or maybe I should do it by default
> 
> added inlay hints (disabled by default): <img alt="image" width="241" src="https://private-user-images.githubusercontent.com/46503702/333454321-1c79bd3a-d513-4cda-8508-d3e2b696d041.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDYxNTkzNjAsIm5iZiI6MTc0NjE1OTA2MCwicGF0aCI6Ii80NjUwMzcwMi8zMzM0NTQzMjEtMWM3OWJkM2EtZDUxMy00Y2RhLTg1MDgtZDNlMmI2OTZkMDQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTAyVDA0MTEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYjY4ZWMyYThkYmM1OGM2Njk4M2FkOWZhOWY0OTgxN2ZkMWM2ZmYzNmZiZjhhNDJlMTM3MDA0N2JlNDQ4MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.abpEnSahFTRo-anqEoHDQ8lkg-BcAQ7U3E-5s8mnrGQ">
> 
> Added auto completion trigger for attributes (enabled by default)

What setting do I need to enable to be able to tab through props like in your second picture? When I click "Add missing attributes" in the QuickFix menu, the cursor moves the then end of the component tag and there is no placeholders to enter prop values.

![Image](https://github.com/user-attachments/assets/3278feed-71e6-415b-9124-4745d75da7fa)

**Comment by zardoy** [comment]
Yes that's expected

**Comment by thrivingproject** [comment]
The problem is that when I click "Add missing attributes", I don't get the placeholders need to immediatly starting typing the prop values. I have to move the cursor with either the arrow keys or my mouse. In your picture when you click add missing attributes you get places holders that you can tab through. This is what I'm trying to get. For example, you have 

`<C a={|} b={|} c={|}></C>`

where the bars `|` are placeholders, and your cursor starts within the brackets of the prop `a`. Then you can immediately start typing the value for prop `a`, and then press tab to move your cursor to the value of prop `b`, and then repeat. But I'm not getting the same result. When I click add missing attributes I get

`<C a={} b={} c={}|></C>`

where there are no placeholders and my cursor is placed at the end of the opening tag for the component `<C></C>`. It's kinda hard to explain. Is there a setting I have to change to reproduce what you showed in the picture instead of getting what I get in the GIF?

**Comment by zardoy** [comment]
No, there is no setting to fix a bug and TypeScript limitation. It's hard to convert regular edits into snippet edits (though this extension support em)
