### ISSUE TITLE
[Bug] Will cause Search in Editor Symbol include symbols in node_modules

### ISSUE THREAD

**Issue by tjx666** [zardoy/typescript-vscode-plugins#209]
With shortcut `cmd + t`：

<img width="1512" alt="image" src="https://github.com/zardoy/typescript-vscode-plugins/assets/41773861/3ac1a82c-f340-4e91-8ef3-3eef775abb09">

If I disable this extension, works fine.
Maybe a related settings: `"typescript.workspaceSymbols.excludeLibrarySymbols": true,`

This issue cost my much time to locate, I had ever think it may be vscode self or ts issue.

**Comment by zardoy** [comment]
> This issue cost my much time to locate

A general rule to find quickly find issues: first try to reload with extensions disabled (command), then use extensions bisect.
