### ISSUE TITLE
Custom Label Search

### ISSUE THREAD

**Issue by akomm** [zardoy/typescript-vscode-plugins#211]
What do you think about this? Could be dope IMO:

https://github.com/microsoft/vscode/issues/214770

**Comment by zardoy** [comment]
https://github.com/microsoft/vscode/issues/214770 this is vscode bug, custom labels search is supported: https://code.visualstudio.com/updates/v1_89#_custom-editor-labels-in-quick-open

also this feature is unrelated to typescript language experience, but thanks for asking.
