### ISSUE TITLE
[PERF] `tsEssentialPlugins.methodSnippets.previewSignature`

### ISSUE THREAD

**Issue by svipas** [zardoy/typescript-vscode-plugins#221]
I really like this setting, but as mentioned in description of this setting - performance isn't great when there are a lot of items. Thinking maybe caching would help in this situation? Just that probably revalidating stale cache would be complex...

**Comment by zardoy** [comment]
https://github.com/zardoy/typescript-vscode-plugins/issues/164 can't invalidate on lock file changes

**Comment by svipas** [comment]
Sorry forgot that I actually created this long time ago 😄
