### ISSUE TITLE
["Keywords Insert Text"] Remove space from `return ` in some cases

### ISSUE THREAD

**Issue by AgentRBY** [zardoy/typescript-vscode-plugins#57]
Hi. First, thx for good plugin!

I propose to make an improvement to the Keywords Insert Text feature. If the person entered 'return' and then ';', then remove the space between them that was inserted.

**Comment by zardoy** [comment]
> I propose to make an improvement to the Keywords Insert Text feature.

I'll definetely be doing a lot of improvements for this features, and yeah I'm really interested in cases, where I should make improvements first. But I ddon't understand your case. Just a miniumum code example is welcome!

**Comment by AgentRBY** [comment]
Here. I would like the space after return to be removed if there is a ;, since the function will not return anything and it is useless. Of course, this is a trifle, but still :)
![Code_EFrNtaLyxC](https://user-images.githubusercontent.com/68181944/200041850-78a998f8-5507-40a0-b9c2-0247b4397553.gif)

**Comment by zardoy** [comment]
Sorry for the delay here. It's my fault here as when I was initially building this feature I was using WebStorm's out-of-box feature as reference. Now I see that WebStorm never included space to the `return` keyword.

So there are 2 ways of solving this:

- Just remove adding space to `return` to align behavior with WS
- Or preserve space for `return` and handle case you described above: after hitting `Enter` or `;` remove added space. It could be useful for `Enter` as user might not have enabled `"files.trimTrailingWhitespace": true` for some reason, and would cause trailing whitespaces to be saved.

What do you think?

**Comment by AgentRBY** [comment]
I think the second variant would be better, but make a setting that allows you to remove some words (including `return`) from this list

**Comment by zardoy** [comment]
> but make a setting that allows you to remove some words (including return) from this list

You can do it today with the same `tsEssentialPlugins.replaceSuggestions` setting:

```jsonc
"tsEssentialPlugins.replaceSuggestions": [
// remove space from specific keywords
  {
    "suggestion": "return",
    "filter": {
      "kind": "keyword"
    },
    "patch": {
      "insertText": "return"
    }
  },
// add space to specific keywords
  {
    "suggestion": "import",
    "filter": {
      "kind": "keyword"
    },
    "patch": {
      "insertText": "import "
    }
  }
]
```
