### ISSUE TITLE
Remove Imports From References doesn't work in vue project

### ISSUE THREAD

**Issue by tjx666** [zardoy/typescript-vscode-plugins#94]
extension: volar
takeover mode: yes

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/216640319-170002e2-d9d3-4045-adcd-91ddbe0e1e8a.png">

**Comment by zardoy** [comment]
Hi! I don't really work with Volar much, but just looked at this, and it seems that references features don't work at all.
Not sure is there even a way to fix it for now...
